devices: 
  - id: <DEVICE_ID>
    token: <DEVICE_JWT_TOKEN>
    topic: "device/notification"
    interval: 2 #seconds
    repeat: true
    values:
      - name: "s"
        value: 1
      - name: "u1"
        min: 0.0
        max: 250.0
      - name: "u2"
        min: 0.0
        max: 250.0
      - name: "u3"
        min: 0.0
        max: 250.0
      - name: "i1"
        min: 0.0
        max: 2.0
      - name: "i2"
        min: 0.0
        max: 20.0
      - name: "i3"
        min: 0.0
        max: 20.0
      - name: "p"
        min: 0.0
        max: 4.0
